# Writes OUTPUT, a header with the git commit zchat is built from (empty when unknown), so that /update knows
# whether the running zchat is behind its sources. Run at every build: the file is touched only when the
# commit changes, so nothing is recompiled otherwise.
set(commit "")
if (GIT)
    execute_process(
        COMMAND "${GIT}" -C "${SOURCE_DIR}" rev-parse HEAD
        OUTPUT_VARIABLE commit
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE result)
    if (NOT result EQUAL 0)
        set(commit "")
    endif()
endif()

set(content "#pragma once\n\n// Generated by cmake/commit.cmake.\n#define ZCHAT_COMMIT \"${commit}\"\n")
set(old "")
if (EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
endif()
if (NOT old STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
